-- MySQL Script generated by MySQL Workbench
-- Fri Mar 14 14:25:58 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
SHOW WARNINGS;
-- -----------------------------------------------------
-- Schema knowyourrights
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `knowyourrights` ;

-- -----------------------------------------------------
-- Schema knowyourrights
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `knowyourrights` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
SHOW WARNINGS;
USE `knowyourrights` ;

-- -----------------------------------------------------
-- Table `knowyourrights`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `knowyourrights`.`categories` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `knowyourrights`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(25) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `knowyourrights`.`comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `knowyourrights`.`comments` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `knowyourrights`.`comments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `post_id` INT NULL DEFAULT NULL,
  `user_id` INT NULL DEFAULT NULL,
  `content` TEXT NOT NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `comments_ibfk_1`
    FOREIGN KEY (`post_id`)
    REFERENCES `knowyourrights`.`posts` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `comments_ibfk_2`
    FOREIGN KEY (`user_id`)
    REFERENCES `knowyourrights`.`users` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE INDEX `post_id` ON `knowyourrights`.`comments` (`post_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `user_id` ON `knowyourrights`.`comments` (`user_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `knowyourrights`.`connections`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `knowyourrights`.`connections` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `knowyourrights`.`connections` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `requester_id` INT NULL DEFAULT NULL,
  `receiver_id` INT NULL DEFAULT NULL,
  `status` ENUM('pending', 'accepted', 'blocked') NOT NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `connections_ibfk_1`
    FOREIGN KEY (`requester_id`)
    REFERENCES `knowyourrights`.`users` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `connections_ibfk_2`
    FOREIGN KEY (`receiver_id`)
    REFERENCES `knowyourrights`.`users` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE UNIQUE INDEX `connections_requester_id_receiver_id` ON `knowyourrights`.`connections` (`requester_id` ASC, `receiver_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `receiver_id` ON `knowyourrights`.`connections` (`receiver_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `knowyourrights`.`contacts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `knowyourrights`.`contacts` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `knowyourrights`.`contacts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL DEFAULT NULL,
  `number` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `contacts_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `knowyourrights`.`users` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE UNIQUE INDEX `number` ON `knowyourrights`.`contacts` (`number` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `user_id` ON `knowyourrights`.`contacts` (`user_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `knowyourrights`.`educations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `knowyourrights`.`educations` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `knowyourrights`.`educations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `university` VARCHAR(255) NOT NULL,
  `college` VARCHAR(255) NOT NULL,
  `department` VARCHAR(255) NOT NULL,
  `degree` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `knowyourrights`.`job_appliers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `knowyourrights`.`job_appliers` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `knowyourrights`.`job_appliers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL DEFAULT NULL,
  `job_id` INT NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `job_appliers_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `knowyourrights`.`users` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `job_appliers_ibfk_2`
    FOREIGN KEY (`job_id`)
    REFERENCES `knowyourrights`.`jobs` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE INDEX `user_id` ON `knowyourrights`.`job_appliers` (`user_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `job_id` ON `knowyourrights`.`job_appliers` (`job_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `knowyourrights`.`job_reports`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `knowyourrights`.`job_reports` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `knowyourrights`.`job_reports` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL DEFAULT NULL,
  `job_id` INT NULL DEFAULT NULL,
  `roport_type` ENUM('SPAM', 'ABUSE', 'OTHER') NOT NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `job_reports_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `knowyourrights`.`users` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `job_reports_ibfk_2`
    FOREIGN KEY (`job_id`)
    REFERENCES `knowyourrights`.`jobs` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE INDEX `user_id` ON `knowyourrights`.`job_reports` (`user_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `job_id` ON `knowyourrights`.`job_reports` (`job_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `knowyourrights`.`jobs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `knowyourrights`.`jobs` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `knowyourrights`.`jobs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `authorId` INT NOT NULL,
  `desciption` VARCHAR(255) NOT NULL,
  `country` VARCHAR(255) NOT NULL,
  `city` VARCHAR(255) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  `job_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `jobs_ibfk_1`
    FOREIGN KEY (`job_id`)
    REFERENCES `knowyourrights`.`users` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE INDEX `job_id` ON `knowyourrights`.`jobs` (`job_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `knowyourrights`.`lawyer_docs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `knowyourrights`.`lawyer_docs` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `knowyourrights`.`lawyer_docs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `lawyerId` INT NOT NULL,
  `idPath` VARCHAR(255) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  `lawyer_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `lawyer_docs_ibfk_1`
    FOREIGN KEY (`lawyer_id`)
    REFERENCES `knowyourrights`.`lawyers` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE INDEX `lawyer_id` ON `knowyourrights`.`lawyer_docs` (`lawyer_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `knowyourrights`.`lawyer_educations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `knowyourrights`.`lawyer_educations` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `knowyourrights`.`lawyer_educations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `lawyer_id` INT NULL DEFAULT NULL,
  `education_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `lawyer_educations_ibfk_1`
    FOREIGN KEY (`lawyer_id`)
    REFERENCES `knowyourrights`.`lawyers` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `lawyer_educations_ibfk_2`
    FOREIGN KEY (`education_id`)
    REFERENCES `knowyourrights`.`educations` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE UNIQUE INDEX `lawyer_educations_education_id_lawyer_id_unique` ON `knowyourrights`.`lawyer_educations` (`lawyer_id` ASC, `education_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `education_id` ON `knowyourrights`.`lawyer_educations` (`education_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `knowyourrights`.`lawyers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `knowyourrights`.`lawyers` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `knowyourrights`.`lawyers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL DEFAULT NULL,
  `law_firm` VARCHAR(255) NOT NULL,
  `license_number` VARCHAR(255) NOT NULL,
  `summery` TEXT NULL DEFAULT NULL,
  `authority` ENUM('training', 'approved', 'consultant') NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `lawyers_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `knowyourrights`.`users` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE UNIQUE INDEX `license_number` ON `knowyourrights`.`lawyers` (`license_number` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `user_id` ON `knowyourrights`.`lawyers` (`user_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `knowyourrights`.`messages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `knowyourrights`.`messages` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `knowyourrights`.`messages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sender_id` INT NULL DEFAULT NULL,
  `receiver_id` INT NULL DEFAULT NULL,
  `content` TEXT NOT NULL,
  `is_read` TINYINT(1) NULL DEFAULT '0',
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `messages_ibfk_1`
    FOREIGN KEY (`sender_id`)
    REFERENCES `knowyourrights`.`users` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `messages_ibfk_2`
    FOREIGN KEY (`receiver_id`)
    REFERENCES `knowyourrights`.`users` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE INDEX `sender_id` ON `knowyourrights`.`messages` (`sender_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `receiver_id` ON `knowyourrights`.`messages` (`receiver_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `knowyourrights`.`notifications`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `knowyourrights`.`notifications` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `knowyourrights`.`notifications` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `message` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `knowyourrights`.`photos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `knowyourrights`.`photos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `knowyourrights`.`photos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `photo_path` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `knowyourrights`.`post_categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `knowyourrights`.`post_categories` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `knowyourrights`.`post_categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `post_id` INT NULL DEFAULT NULL,
  `category_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `post_categories_ibfk_1`
    FOREIGN KEY (`post_id`)
    REFERENCES `knowyourrights`.`posts` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `post_categories_ibfk_2`
    FOREIGN KEY (`category_id`)
    REFERENCES `knowyourrights`.`categories` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE UNIQUE INDEX `post_categories_category_id_post_id_unique` ON `knowyourrights`.`post_categories` (`post_id` ASC, `category_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `category_id` ON `knowyourrights`.`post_categories` (`category_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `knowyourrights`.`post_photos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `knowyourrights`.`post_photos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `knowyourrights`.`post_photos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `post_id` INT NULL DEFAULT NULL,
  `photo_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `post_photos_ibfk_1`
    FOREIGN KEY (`post_id`)
    REFERENCES `knowyourrights`.`posts` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `post_photos_ibfk_2`
    FOREIGN KEY (`photo_id`)
    REFERENCES `knowyourrights`.`photos` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE UNIQUE INDEX `post_photos_photo_id_post_id_unique` ON `knowyourrights`.`post_photos` (`post_id` ASC, `photo_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `photo_id` ON `knowyourrights`.`post_photos` (`photo_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `knowyourrights`.`post_reports`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `knowyourrights`.`post_reports` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `knowyourrights`.`post_reports` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL DEFAULT NULL,
  `post_id` INT NULL DEFAULT NULL,
  `roport_type` ENUM('SPAM', 'ABUSE', 'OTHER') NOT NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `post_reports_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `knowyourrights`.`users` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `post_reports_ibfk_2`
    FOREIGN KEY (`post_id`)
    REFERENCES `knowyourrights`.`posts` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE INDEX `user_id` ON `knowyourrights`.`post_reports` (`user_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `post_id` ON `knowyourrights`.`post_reports` (`post_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `knowyourrights`.`posts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `knowyourrights`.`posts` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `knowyourrights`.`posts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `author_id` INT NULL DEFAULT NULL,
  `title` VARCHAR(255) NOT NULL,
  `content` TEXT NOT NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `posts_ibfk_1`
    FOREIGN KEY (`author_id`)
    REFERENCES `knowyourrights`.`users` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE INDEX `author_id` ON `knowyourrights`.`posts` (`author_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `knowyourrights`.`profile_images`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `knowyourrights`.`profile_images` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `knowyourrights`.`profile_images` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL DEFAULT NULL,
  `image_path` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `profile_images_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `knowyourrights`.`users` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE INDEX `user_id` ON `knowyourrights`.`profile_images` (`user_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `knowyourrights`.`reacts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `knowyourrights`.`reacts` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `knowyourrights`.`reacts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL DEFAULT NULL,
  `post_id` INT NULL DEFAULT NULL,
  `reaction` ENUM('like', 'love', 'haha', 'wow', 'sad', 'angry') NOT NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `reacts_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `knowyourrights`.`users` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `reacts_ibfk_2`
    FOREIGN KEY (`post_id`)
    REFERENCES `knowyourrights`.`posts` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE INDEX `user_id` ON `knowyourrights`.`reacts` (`user_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `post_id` ON `knowyourrights`.`reacts` (`post_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `knowyourrights`.`sessions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `knowyourrights`.`sessions` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `knowyourrights`.`sessions` (
  `sid` VARCHAR(36) NOT NULL,
  `expires` DATETIME NULL DEFAULT NULL,
  `data` TEXT NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`sid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `knowyourrights`.`shares`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `knowyourrights`.`shares` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `knowyourrights`.`shares` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL DEFAULT NULL,
  `post_id` INT NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `shares_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `knowyourrights`.`users` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `shares_ibfk_2`
    FOREIGN KEY (`post_id`)
    REFERENCES `knowyourrights`.`posts` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE INDEX `user_id` ON `knowyourrights`.`shares` (`user_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `post_id` ON `knowyourrights`.`shares` (`post_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `knowyourrights`.`user_notifications`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `knowyourrights`.`user_notifications` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `knowyourrights`.`user_notifications` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL DEFAULT NULL,
  `notification_id` INT NOT NULL,
  `is_read` TINYINT(1) NULL DEFAULT '0',
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `user_notifications_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `knowyourrights`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `user_notifications_ibfk_2`
    FOREIGN KEY (`notification_id`)
    REFERENCES `knowyourrights`.`notifications` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE UNIQUE INDEX `user_notifications_notification_id_user_id_unique` ON `knowyourrights`.`user_notifications` (`notification_id` ASC, `user_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `user_id` ON `knowyourrights`.`user_notifications` (`user_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `knowyourrights`.`user_reports`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `knowyourrights`.`user_reports` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `knowyourrights`.`user_reports` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL DEFAULT NULL,
  `reporter_id` INT NULL DEFAULT NULL,
  `report_type` ENUM('SPAM', 'ABUSE', 'OTHER') NOT NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `user_reports_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `knowyourrights`.`users` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `user_reports_ibfk_2`
    FOREIGN KEY (`reporter_id`)
    REFERENCES `knowyourrights`.`users` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE INDEX `user_id` ON `knowyourrights`.`user_reports` (`user_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `reporter_id` ON `knowyourrights`.`user_reports` (`reporter_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `knowyourrights`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `knowyourrights`.`users` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `knowyourrights`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(255) NOT NULL,
  `last_name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `role` ENUM('visitor', 'lawyer', 'admin') NULL DEFAULT 'visitor',
  `country` VARCHAR(255) NULL DEFAULT NULL,
  `city` VARCHAR(255) NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;
CREATE UNIQUE INDEX `email` ON `knowyourrights`.`users` (`email` ASC) VISIBLE;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
