import Navbar from "@/components/Navbar";
import "./globals.css";
import NavbarWrapper from "@/components/NavbarWrapper";

export const metadata = {
  title: "Know Your Rights",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NavbarWrapper>
          <Navbar />
        </NavbarWrapper>
        {children}
      </body>
    </html>
  );
}
