import Navbar from "@/components/Navbar";
import "./globals.css";
import NavbarWrapper from "@/components/NavbarWrapper";
import { Toaster } from "@/components/ui/sonner";
import ThemeProvider from "@/components/ThemeProvider";

export const metadata = {
  title: "Know Your Rights",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider>
          <NavbarWrapper>
            <Navbar />
          </NavbarWrapper>
          {children}
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
